### ISSUE TITLE
Adding this dependency causes runtime failure

### ISSUE THREAD

**Issue by SpicySyntax** [googleapis/java-secretmanager#706]
#### Environment details

1. Specify the API at the beginning of the title. Google Cloud Secrets: google-cloud-secretmanager
2. OS type and version:
Mac OS
3. Java version: 
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
4.  version(s): 2.1.1

#### Steps to reproduce

  1. Add dependency
  2. Run maven build
  3. run docker build
  4. run docker image via docker-compose

NOTE: after adding this dependency to my maven project, my dockerized application fails at runtime

#### Code example

```docker
FROM eclipse-temurin:17.0.1_12-jdk-alpine

ARG JAVA_OPTS

# Setup non-root user
ARG USER=default
ENV HOME /home/$USER

# install sudo as root
# RUN apk add --update sudo

# add new user
RUN adduser -D $USER 
        # && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
        # && chmod 0440 /etc/sudoers.d/$USER

USER $USER
WORKDIR $HOME

COPY target/my-uber-*.jar ./my-jar.jar
EXPOSE 8080
# -XX:+UseCGroupMemoryLimitForHeap
CMD java -XX:+UnlockExperimentalVMOptions -Dcom.sun.management.jmxremote ${JAVA_OPTS} -jar my-jar.jar

```

#### Stack trace
When running the docker image
```
token-service_1       | Error: A JNI error has occurred, please check your installation and try again
token-service_1       | Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
token-service_1       |         at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:340)
token-service_1       |         at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:282)
token-service_1       |         at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:321)
token-service_1       |         at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:234)
token-service_1       |         at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:762)
token-service_1       |         at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1033)
token-service_1       |         at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:72)
token-service_1       |         at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:883)
token-service_1       |         at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:848)
token-service_1       |         at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
token-service_1       |         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
token-service_1       |         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
token-service_1       |         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
token-service_1       |         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
token-service_1       |         at java.base/java.lang.Class.forName0(Native Method)
token-service_1       |         at java.base/java.lang.Class.forName(Class.java:467)
token-service_1       |         at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:780)
token-service_1       |         at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:675)
```

NOTE: this seems related to the following [discussion](https://discuss.gradle.org/t/adding-google-cloud-secretmanager-dependency-will-cause-could-not-find-or-load-main-class-error/40375)

**Comment by eaball35** [comment]
Thanks for opening an issue. Can I ask what version of maven you're using?

**Comment by SpicySyntax** [comment]
```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /Users/njp020/.sdkman/candidates/maven/current
Java version: 17.0.1, vendor: Eclipse Adoptium, runtime: /Users/njp020/.sdkman/candidates/java/17.0.1-tem
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```
I tried using the following maven-shade-plugin config, but it produced other errors when building the uber JAR
```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-shade-plugin</artifactId>
  <version>3.2.4</version>
  <executions><execution>
  <phase>package</phase>
<goals>
  <goal>shade</goal>
</goals>
<configuration>
  <filters>
    <filter>
      <artifact>com.google.cloud:*</artifact>
        <excludes>
          <exclude>META-INF/*.SF</exclude>
          <exclude>META-INF/*.DSA</exclude>
           <exclude>META-INF/*.RSA</exclude>
          <exclude>META-INF/*.MF</exclude>
        </excludes>
    </filter>
   </filters>
</configuration>
.....
```

I have been using 'zip' to remove files that trigger this exception from 'META-INF/' e.g.

```bash
zip -d ./my-project.jar 'META-INF/*.SF' 'META-INF/*.RSA' 'META-INF/*SF' 
```

**Comment by suztomo** [comment]
Would you create a minimum reproducible GitHub project?

(I wonder what's special in this google-cloud-secretmanager. I don't see this library in your comments.)

**Comment by meltsufin** [comment]
Closing due to lack of responses from OP.
