### ISSUE TITLE
Cant use com.google.protobuf:protobuf-java:jar:3.20.1 in data proc cluster because of some dependency issue

### ISSUE THREAD

**Issue by kaushalzoom** [googleapis/java-secretmanager#786]
We are trying to access secrete manager in GCP using google secrete manager library. Mvn depdencies below in spark-scala project.
<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>libraries-bom</artifactId>
			<version>25.4.0</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-secretmanager</artifactId>
			<version>2.2.0</version>
		</dependency>
Getting below error when spark job submits on data proc cluster. 

Exception in thread "grpc-default-executor-0" java.lang.IllegalAccessError: tried to access field com.google.protobuf.AbstractMessage.memoizedSize from class com.google.cloud.secretmanager.v1.AccessSecretVersionRequest
        at com.google.cloud.secretmanager.v1.AccessSecretVersionRequest.getSerializedSize(AccessSecretVersionRequest.java:197)
        at io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108)
        at io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:205)
        at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:137)
        at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)
        at io.grpc.internal.DelayedStream$6.run(DelayedStream.java:283)
        at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:182)
        at io.grpc.internal.DelayedStream.access$100(DelayedStream.java:44)
        at io.grpc.internal.DelayedStream$4.run(DelayedStream.java:148)
        at io.grpc.internal.MetadataApplierImpl.finalizeWith(MetadataApplierImpl.java:110)
        at io.grpc.internal.MetadataApplierImpl.apply(MetadataApplierImpl.java:78)
        at io.grpc.auth.GoogleAuthLibraryCallCredentials$1.onSuccess(GoogleAuthLibraryCallCredentials.java:131)
        at com.google.auth.oauth2.OAuth2Credentials$FutureCallbackToMetadataCallbackAdapter.onSuccess(OAuth2Credentials.java:549)
        at com.google.auth.oauth2.OAuth2Credentials$FutureCallbackToMetadataCallbackAdapter.onSuccess(OAuth2Credentials.java:540)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1078)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:141)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:130)
        at com.google.common.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:86)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
        at java.util.concurrent.FutureTask.set(FutureTask.java:233)
        at java.util.concurrent.FutureTask.run(FutureTask.java:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

**Comment by meltsufin** [comment]
Do you have a reproducer for the issue?

**Comment by kaushalzoom** [comment]
Hi mletsufin

all i did is added google secrete manage library in my spark-scala program which i am running on data proc cluster. And follow the code snippet to access secrete as per code snippet given on the google portal.

**Comment by averikitsch** [comment]
Please try updating to the latest version and reopen if you continue to experience this issue.
